apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
        - name: argo-app-container
          image: ghcr.io/EldarDL/argocd-ci-cd-pipeline/argo-app:c6c7b2fb47fece190d06cd280dc66b29aa6eb6d9
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-docker-secret
