apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-1
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: infra
    repoURL: 'git@github.com:<your-github-account>/<your-github-repo>.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
