apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
        - name: argo-app-container
          image: ghcr.io/eldardl/directeam-project/argo-app:294334a2d2acf6380a360f3c56a72e749e3af05f
      imagePullSecrets:
        - name: ghcr-docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: argo-app-service
spec:
    type: ClusterIP
    selector:
        app: argo-app
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: argo-app-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: argo-app-service
            number: 8080
            port: null
        path: /
        pathType: Prefix


