apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
        - name: argo-app-container
          image: ghcr.io/eldardl/directeam-project/argo-app:09469dfda8a9581c73f9ed02933d630cbe89ba18
      imagePullSecrets:
        - name: ghcr-docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: argo-app-service
spec:
    type: ClusterIP
    selector:
        app: argo-app
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: argo-app-ingress
spec:
  rules:
  - host: argo-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-app-service
            port:
              number: 80


