name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      shell: bash
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
    - name: Authenticate with GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Push image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}

  update-manifest:

    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update manifest
      run: |
        echo ${{ github.repository }}
        sed -i 's|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|' infra/deployment.yaml

    - name: Commit manifest
      run: |
          git config --global user.name "${{ secrets.name }}"
          git config --global user.email "${{ secrets.email }}"
          git add -A
          git commit -m "Update manifest to ${{ github.sha }}"
          git push


